[build]
  command = "npm run build"
  publish="/build"
  base = "/"

[[redirects]]
  from = "/api"
  to = "https://api.themoviedb.org/3"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
